[package]
name = "calc"
version = "0.1.0"
authors = ["Matthew Kousoulas <shaman.kous@gmail.com>"]

[workspace]

[dependencies]
lib = { path = "lib" }
termion = "1"
# syn = "0.15"
# quote = "0.6"

# [lib]
# proc-macro = true

